### ISSUE TITLE
7B lite 单卡没有达到报的点数，请教可能的原因。

### ISSUE THREAD

**Issue by yanghu819** [luogen1996/LaVIN#15]
结果是
{'acc_natural': '86.72', 'acc_social': '94.26', 'acc_language': '84.00', 'acc_has_text': '85.43', 'acc_has_image': '84.38', 'acc_no_context': '87.74', 'acc_grade_1_6': '88.58', 'acc_grade_7_12': '85.83', 'acc_average': '87.60'}
结果低2个点。

用的2080ti显卡
训练和推理：
CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node 1 --master_port 11111 train.py \
    --llm_model 7B\
    --llama_model_path /data/jupyter/lavin/data/weights \
    --data_path ../data/alpaca_data.json \
    --max_seq_len 512 \
    --batch_size 2 \
    --accum_iter 16 \
    --epochs 20 \
    --warmup_epochs 2 \
    --blr 9e-3 \
    --weight_decay 0.02 \
    --output_dir ./LaVIN-7B-lite/\
    --adapter_type attn\
    --adapter_dim 8\
    --adapter_scale 1\
    --n_prompt 6 \
    --prompt_format QCM-ALE \
    --temperature 10.\
    --visual_adapter_type router \
    --gradient_checkpointing \
    --bits 4bit \
    --cpu_load

CUDA_VISIBLE_DEVICES=0 torchrun --nproc_per_node 1  eval.py \
    --ckpt_dir ../data/weights/ \
    --llm_model 7B\
    --tokenizer_path ../data/weights/tokenizer.model \
    --data_root ../data \
    --caption_file ../data/captions.json \
    --adapter_path ./LaVIN-7B-lite/checkpoint-19.pth \
    --adapter_type attn \
    --adapter_dim 8 \
    --adapter_scale 1 \
    --prompt_format QCM-ALE \
    --max_batch_size 8\
    --max_seq_len 512 \
    --split test \
    --n_prompt 6 \
    --temperature 10.\
    --visual_adapter_type router\
    --bits 4bit \
    --cpu_load

**Comment by yanghu819** [comment]
overall accuracy:  88.49327988681914{'acc_natural': '88.10', 'acc_social': '94.04', 'acc_language': '84.82', 'acc_has_text': '87.00', 'acc_has_image': '86.22', 'acc_no_context': '88.08', 'acc_grade_1_6': '89.68', 'acc_grade_7_12': '86.35', 'acc_average': '88.49'}

2*16改为1*32之后结果提升了

**Comment by verigle** [comment]
> overall accuracy: 88.49327988681914{'acc_natural': '88.10', 'acc_social': '94.04', 'acc_language': '84.82', 'acc_has_text': '87.00', 'acc_has_image': '86.22', 'acc_no_context': '88.08', 'acc_grade_1_6': '89.68', 'acc_grade_7_12': '86.35', 'acc_average': '88.49'}
> 
> 2_16改为1_32之后结果提升了

请问 `216改为132` 是指改的哪个地方呢？

**Comment by yanghu819** [comment]
--batch_size 2
--accum_iter 16
改为
--batch_size 1
--accum_iter 32
2080ti上复现的

**Comment by Pefect96** [comment]
> --batch_size 2 --accum_iter 16 改为 --batch_size 1 --accum_iter 32 2080ti上复现的

请问batch_size改为1之后，在单卡GPU上训练需要多久呢？
