### ISSUE TITLE
[data]请问在MME benchmark上进行评测的模型是只使用了instrcution数据（约210k）训练的嘛？

### ISSUE THREAD

**Issue by Aopolin-Lv** [luogen1996/LaVIN#16]
rt

**Comment by luogen1996** [comment]
是的，权重在https://drive.google.com/file/d/1rHQNSaiGzFHYGgsamtySPYnd5AW4OE9j/view?usp=share_link

**Comment by Aopolin-Lv** [comment]
> 是的，权重在https://drive.google.com/file/d/1rHQNSaiGzFHYGgsamtySPYnd5AW4OE9j/view?usp=share_link

谢谢回复！
