### ISSUE TITLE
typo in your citation~

### ISSUE THREAD

**Issue by WizardMx** [luogen1996/LaVIN#3]

**Comment by WizardMx** [comment]
mb, not your citation but your paper's citation information
@article{luo2023cheap,
 title={Cheap and Quick: Efficient Vision-Language Instruction Tuning for Large Language Models},
 author={Luo, Gen and  Zhou, Yiyi and Ren, Tianhe and Chen, Shengxin **abd** Sun, Xiaoshuai and Ji, Rongrong},
 journal={arXiv preprint arXiv:2305.15023},
 year={2023}
  }

**Comment by luogen1996** [comment]
Thanks for your help, we have revised the typos.
