### ISSUE TITLE
A little confusion of Figure 2

### ISSUE THREAD

**Issue by WizardMx** [luogen1996/LaVIN#4]
When Routing Weights Generation block processes Modality Token and generates weights for fa1 and fa2, weight matrix and bias Wm and bm are used. Are these two parameters going to be trained through training? As I understand, yes, but in the figure there isn't a little flame icon attached.

**Comment by luogen1996** [comment]
Yes, it's learnable.   Mixture-of-Modality Adapter (MM-Adapter) is attached with a flame icon in Figure 2, and Wm and bm are part of the MM-Adapter.

**Comment by jingzhengli** [comment]
Thanks for your quick reply.

**Comment by WizardMx** [comment]
makes perfect sense, thx! Fantastic work btw
