### ISSUE TITLE
LaVin-7B model on task Multimodal ChatBot

### ISSUE THREAD

**Issue by Dicomsky** [luogen1996/LaVIN#5]
Would you mind releasing LaVin-7B model on task Multimodal ChatBot?
I'm interested in your work but I have 4 3090Ti and no enough resourse to fully train a LaVin-7B model, and lavin-13B is too large.

**Comment by luogen1996** [comment]
We haven't experimented with the multimodal chatbot on the 7B model. However, we are trying to accelerate the training and save GPU memory, looking forward our updates.

**Comment by Dicomsky** [comment]
Thank you for your reply!

**Comment by 18445864529** [comment]
Any update on this? the GPU requirement 55G for 13B chatbot is not affordable on many GPU types. Would be glad if you could release a 7B chatbot checkpoint or reduce the memory usage to under 40G, for the chatbot experiment. Thanks.
