### ISSUE TITLE
GPT-4 evaluation

### ISSUE THREAD

**Issue by WizardMx** [luogen1996/LaVIN#6]
How do you evaluate your response via GPT-4? Feed him the image and its response, then ask him to give a score out of 10?

**Comment by luogen1996** [comment]
We use the  GPT-assisted evaluation from llava,  which feeds GPT4 with the object categories, boxes  and image captions, and asks it to evaluate the given responses.   See the details in [LLaVA](https://github.com/haotian-liu/LLaVA#evaluation).
