### ISSUE TITLE
请问有考虑用 lora来替换部分adapter吗？

### ISSUE THREAD

**Issue by CheungZeeCn** [luogen1996/LaVIN#7]
RT

**Comment by luogen1996** [comment]
暂时没有。一是没有必要，二是我们觉得lora的性能不如repadapter，我们之前的论文有做过实验 。如果你感兴趣的话可以做一下这方面的实验，我们欢迎任何人贡献新的代码和权重。

**Comment by CheungZeeCn** [comment]
@luogen1996  嗯嗯 后来跟着ref 看到了相关描述 感谢答疑。
